---
version: "3.9"

volumes:
    bot-logs:
        external: true

services:
    app:
        image: ${IMAGE}:${TAG}
        volumes:
            - bot-logs:/app/logs
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
