#cloud-config
users:
    - name: ${username}
      groups: sudo
      sudo: ALL=(ALL) NOPASSWD:ALL
      shell: /bin/bash
      hashed_passwd: ${passwd}
      lock_passwd: false
      ssh-authorized-keys:
          - ${ssh_key_path}

runcmd:
    - sudo usermod -aG docker ${username}
    - sudo docker volume create bot-logs
